<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  0 => '',
  ' use:' => '',
  ' welcome to {siteName}!' => '',
  'Access denied by cochanges\\frontend\\modules\\auth\\controllers\\ValidateController' => '',
  'Code has expired. {a}Send the code again{/a}' => '',
  'Code re-sent ' => '',
  'Code sent ' => '',
  'Confirmation code for {siteName} ' => '',
  'If you are asked not to send you the code, please ignore the letter. ' => '',
  'If you forgot your password, you can enter a new one. ' => '',
  'If you haven’t requested a password change, we’re sorry to disturb you, and just ignore this letter.' => '',
  'Incorrect code' => '',
  'Incorrect e-mail.Please, enter a correct e-mail address.' => '',
  'Login:' => '',
  'Oops, something went wrong. Please, try again' => '',
  'Oops, something went wrong. Please, try again.' => '',
  'Oops, something went wrong. Please, try again."' => '',
  'Oops, something went wrong. Send the code again' => '',
  'Oops, something went wrong. Send the code again?' => '',
  'Password from the e-mail' => '',
  'Password:' => '',
  'Please choose a profile' => '',
  'Please choose a region from the list' => '',
  'Please enter your e-mail' => '',
  'Please, fill in' => '',
  'Please, go to the link:' => '',
  'SMS delivery is failed' => '',
  'Thanks! Password reset instructions were sent to your e-mail.' => '',
  'The code can not be issued earlier than 3 minutes from the time of dispatch of the previous' => '',
  'The password doesn’t match. If you can’t remember the password, press "Change the Password"' => '',
  'There is no such e-mail address in our base. Please, sign up' => '',
  'There were one or more errors in your submission. Please correct the marked fields below.' => '',
  'This email address already exists. Please log In if you already registered' => '',
  'This phone number already exists' => '',
  'This user is blocked' => '',
  'To log in to ' => '',
  'We send you a verification code. A one-time code, your password has not changed. After entering the verification code, you can change your password in your profile. ' => '',
  'You may change the password after' => '',
  'You must accept terms and conditions' => '',
  'Your account is created. To log in, enter the password sent to your e-mail' => '',
  'Your code: ' => '',
  'Your confirmation code has been sent to your email address' => '',
  'Your password on {siteName} ' => '',
  'You’ve signed up to {siteName}' => '',
  'did you forget your password?' => '',
  'logging in on' => '',
  'thank you with us again! ' => '',
  'will send you a confirmation code ' => '',
);
