<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  0 => '',
  ' - social initiative support platform' => '',
  ' The file extension jpg | jpeg | png | tiff | gif.' => '',
  ' develops a participatory society, involving locals in changing what`s around them. The platform helps to make life better in a particular courtyard, district and a whole city.' => '',
  '- Create groups and participate in {br /}' => '',
  '- To collect and give money to socially useful projects and actions {br /} ' => '',
  '- To create excuses, handling, voting events {br /}' => '',
  'A server error occurred, please try later.' => '',
  'Add' => '',
  'After confirmation, you will discover many new features on {siteName}. You`ll be able to: {br /}' => '',
  'After confirmation, you will discover many new features to the project {siteName} ' => '',
  'Cancel' => '',
  'Change the password' => '',
  'Code is in SMS' => '',
  'Confirm your phone number' => '',
  'Confirmation code ' => '',
  'Create an account' => '',
  'Do you really want to make this account primary? ' => '',
  'Enter the e-mail address provided during the registration, and press "Change the Password". We’ll send you a new password.' => '',
  'False' => '',
  'I accept {userAgreementLink}the terms of use{/userAgreementLink}, agree with processing my personal data and confirm that I am 18.' => '',
  'Image size not more than 5MB. ' => '',
  'Inhabited locality`s name' => '',
  'Log in' => '',
  'Log out' => '',
  'No, thanks' => '',
  'Or sign in through your social network profile' => '',
  'Registration' => '',
  'Remember' => '',
  'Reset the password with a phone number' => '',
  'Select the account under which you want to use {siteName}' => '',
  'Send confirmation code' => '',
  'Settings' => '',
  'There was an error loading the image. ' => '',
  'True' => '',
  'Upload another photo' => '',
  'Yes' => '',
  'You are logged in as' => '',
  'Your e-mail address' => '',
  'Your e-mail address or phone number' => '',
  'Your name' => '',
  'Your password' => '',
  'Your phone number' => '',
  'Your profile picture' => '',
  'Your surname' => '',
  'add' => '',
  'confirm' => '',
  'done' => '',
  'log in' => '',
  'save' => '',
  'Continue' => '',
);
