<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  ' ' => '',
  'COMMENTS' => '',
  'Cancel' => '',
  'Comment' => '',
  'Reply' => '',
  'Save' => '',
  'You have an answer to your comment on {siteName} ' => '',
  'Your contribution to {siteName} has received a new comment' => 'Your contribution to {siteName} has received a new comment',
  'all comments' => '',
  'comment deleted' => '',
  'commented on' => '',
  'comment|comments' => '',
  'on' => '',
  'replied' => '',
  'to your comment in' => '',
  'userpic' => '',
  '{n} answer|{n} answers|{n} answers' => '',
);
