<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'After fulfillment of your promise,{br /}share the results with everyone' => '',
  'Anonymous user' => '',
  'Choose an action' => '',
  'Crowdfunding is finished' => '',
  'Crowdfunding is over<br>The target sum wasn`t collected' => '',
  'Donate' => '',
  'It`s done!' => '',
  'The action is canceled' => '',
  'The action<br /> is failed' => '',
  'The action<br /> is stopped.' => '',
  'The organizator will have {n} days to use the money by purpose.' => '',
  'The promise <br /> is fulfilled' => '',
  'The promise <br /> isn`t fulfilled' => '',
  'The report template with further instructionswill be sent to your{tag}{email}{/tag}.' => '',
  'The time for fulfillment has passed{br /}The promise wasn`t fulfilled' => '',
  'Time for fulfillment' => '',
  'Time for fulfillment has passed. Nothing is done.' => '',
  'To choose an action you have' => '',
  'To register, click on "Give money"' => '',
  'Until the end' => '',
  'Yay! The money is collected!' => '',
  'You donated ' => '',
  'You transferred to the action' => '',
  'You`ll have {n} days to use the money by purpose' => '',
  'collected' => '',
  'collected of {n}' => '',
  'collected {collected}' => '',
  'or you can {tag}cancel the action{/tag}' => '',
  'reports' => '',
  'the action didn`t raise enough funds, but you can transfer your money to other action.' => '',
  'until the end' => '',
  'you donated ' => '',
  'your supporters are waiting! fulfill your promises and share the story!' => '',
  '{n} days left' => '',
  '{n} person | {n} people' => '',
  '{n}day left |{n} days left | {n} days left ' => '',
  '{tag}{collected}{/tag} out of {total}' => '',
  '{tag}{collected}{/tag}{br /} collected' => '',
);
