<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Add' => '',
  'Administrator' => '',
  'Administrator will be removed' => '',
  'Become an expert' => '',
  'Confirm' => '',
  'Continue' => '',
  'E-mail' => '',
  'E-mail or ID' => '',
  'Expert' => '',
  'Expert opinion' => '',
  'Expert will be removed' => '',
  'Form your project`s team, attract experts and administrators' => '',
  'I agree to become an expert on the Internet platform {siteName}' => '',
  'I agree to join the project team on {siteName}' => '',
  'In the project' => '',
  'Invitation{br /}sent' => '',
  'Invite' => '',
  'Invited person`s name' => '',
  'Invited person`s surname' => '',
  'Join' => '',
  'Join project`s team on {siteName}' => '',
  'Name Surname' => '',
  'No' => '',
  'Not found' => '',
  'Permission granted to create my account and accept the rules of {tag}site{/tag}.' => '',
  'Please tell the author the reason why:' => '',
  'Refuse' => '',
  'Send' => '',
  'Subscribe' => '',
  'The invitation {br /} wasn`t accepted.' => '',
  'The page was not found' => '',
  'Unsubscribe' => '',
  'User will be deleted from the project' => '',
  'User will be removed' => '',
  'Want to join in the project {siteName} and develop the city along with all?' => '',
  'Why I don\'t want to join the team' => '',
  'Why I won\'t be an expert' => '',
  'Yes' => '',
  'Your refusal was sent to the author of the project.' => '',
  'administrator' => '',
  'expert' => '',
  'invite' => '',
  'press here to add an' => '',
);
