<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  ' is a local web project  offering user-friendly technologies of participation and interaction.' => '',
  'For authorities {tag} is a convenient tool of interaction with the citizens and feedback. {tag} involves citizens in social life and lets them participate in polls while assigning budget funds.' => '',
  'For cooperation, contact us: ' => '',
  'If you have any questions or problems with the site, contact our helpdesk: ' => '',
  'People living nearby and having similar interests use {tag} for solving common problems and making your city, area or yard better. Thanks to {tag} services, it is very easy to participate in the city’s life. You can change something just with one click without leaving your coach.' => '',
  'Thanks to {tag}, NGOs and public organizations get support from mass media, and the commercial organizations use {tag} for promoting brand’s social image and communicating with the audience.' => '',
  'What is ' => '',
  '{tag} lets the city’s activists involve a great number of people in different initiatives and find like-minded people. Our lawyers help to make appeals to authorities and control their execution. Also crowdfunding actions may be held on {tag}.' => '',
);
