<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Add a photo' => '',
  'Add a rule' => '',
  'Add your life rule' => '',
  'An error has occurred.' => '',
  'An error has occurred. Image size not more than 15MB. The file extension jpg | jpeg | png | tiff | gif.' => '',
  'Become the first' => '',
  'Currently there are no events' => '',
  'Find and invite neighbors' => '',
  'Invitation sent!' => '',
  'Join' => '',
  'Leave' => '',
  'No residents yet' => '',
  'No rules yet' => '',
  'Or join in order to be informed of the place' => '',
  'Place’s rating' => '',
  'Something to share about this place?' => '',
  'Start typing the address of your home, workplace or school' => '',
  'There`s no photo.' => '',
  'add' => '',
  'change the address' => '',
  'events' => '',
  'life rules' => '',
  'photo' => '',
  'residents' => '',
);
