<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Change the address' => '',
  'Change the number' => '',
  'Check your e-mail' => '',
  'Confirm' => '',
  'Confirmation code ' => '',
  'Confirmation email ' => '',
  'Confirmation number ' => '',
  'Continue' => '',
  'Correctly indicate your real name ' => '',
  'Correctly specify your real name ' => '',
  'Done' => '',
  'E-mail' => '',
  'Enter the new number, and we will send {br /} SMS with a confirmation code ' => '',
  'For you created your account with login {tag}{email}{/tag} Now you need to set a password: ' => '',
  'I accept {a}Terms of Service{/a} and confirm that I am 18 years old. ' => '',
  'I accept {tag}the terms of use{/tag}, agree with processing my personal data {br /}and confirm that I am 18.' => '',
  'I accept {tag}the terms of use{/tag},{br /} agree with processing my personal data {br /}and confirm that I am 18.' => '',
  'In the life of the city you wish to {br /} affect the life of the city you {br /} indifferent? ' => '',
  'Login to members' => '',
  'Mobile phone number' => '',
  'Name' => '',
  'Password to login ' => '',
  'Phone number' => '',
  'Please, confirm the e-mail address' => '',
  'Registration' => '',
  'Save' => '',
  'Send again' => '',
  'Set password ' => '',
  'Sign in ' => '',
  'Sign up' => '',
  'Support' => '',
  'Support treatment ' => '',
  'Surname' => '',
  'Telling me about the success {siteName} ' => '',
  'The request has already been sent ' => '',
  'This number we will send {br /} SMS with a confirmation code ' => '',
  'Unable to authenticate via social network ' => '',
  'Verify later ' => '',
  'We have sent a confirmation link to your email {email}{/tag}' => '',
  'We have sent a confirmation link to your email {tag}{email}{/tag}' => '',
  'We`ve sent on the number {phoneNumber}{br /}a text message with the confirmation code' => '',
  'We’ll send you a link you’ll {br /} need to go for the confirmation' => '',
  'You have already sent a request to support this appeal. Check your e-mail for email with a link to confirm. ' => '',
  'log in' => '',
);
