<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Hello, {tag}!' => '',
  'If you have any difficulties or questions, you can contact our support team ({support}) - you are sure to help! ' => '',
  'You offer to subscribe to geotag ' => '',
  'Your {siteName}' => '',
  'find like-minded people to improve your city, neighbourhood, and courtyard together.' => '',
  'follow the most important events in places where you live, work and spend your free time' => '',
  'unite with your neighbours to solve your problems' => '',
  '{inviter} suggests you subscribe to geotag {link}. Why do it now?' => '',
  '{siteName} develops services for people who live nearby and have common interests. By subscribing yourself to the geotag, you will be able to:' => '',
);
