<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Album' => '',
  'Collecting signatures to solve the problem' => '',
  'Contacting authorities' => '',
  'Copy the link and paste it here' => '',
  'Crowdfunding' => '',
  'Description' => '',
  'End date' => '',
  'Event' => '',
  'Event’s starting time' => '',
  'Invite residents to participate' => '',
  'Is voting allowed?' => '',
  'Issue' => '',
  'Learn from the residents' => '',
  'Link' => '',
  'Link to the source' => '',
  'Petition' => '',
  'Poll' => '',
  'Project name' => '',
  'Question' => '',
  'Share news, idea, opinion or share issue' => '',
  'Source`s author' => '',
  'Source`s name' => '',
  'Sponsoring' => '',
  'Start date' => '',
  'Title' => '',
  'To' => '',
  'To the project on making the city better' => '',
  'Total' => '',
  'more' => '',
);
