<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'All' => '',
  'Cities' => '',
  'E-mail' => '',
  'Events' => '',
  'It is impossible to fulfill the search query. Try to simplify it or to search for something else.' => '',
  'Only ' => '',
  'People' => '',
  'Public profiles' => '',
  'Send an invitation' => '',
  'Unfortunately, nothing was found. Try to search for something else.' => '',
  'You may invite him/her by e-mail.' => '',
  'and organizations' => '',
  '{siteName} doesn’t know this person yet.' => '',
);
