<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'After confirming your support, you will become a user of the system {tag}, and your opinion will be reflected on the page treatment and collective letters to be forwarded to the public authorities. ' => '',
  'After the confirmation of your vote, you will be included in the list of people who voted for the importance of the topic and you will have the right to participate, with the author of the topic and other users, in editing the texts of collective letters that are formed within the framework of the issue.' => '',
  'After the confirmation of your vote, you will be included in the list of people who voted for the importance of the topic and you will have the right to participate, with the author of the topic and other users, in editing the texts of collective letters that are formed within the framework of the petition.' => '',
  'An answer received {department}' => '',
  'Ask your friends and acquaintances to support your appeal, and then their votes will be mentioned in the official letter' => '',
  'At the moment, the appeal has collected {signsCount} signatures. If more than 50 people support this appeal, we will print on an official form and send it to the organisation in charge by registered mail.' => '',
  'Based on' => '',
  'Collective petition forwarded {department} ' => '',
  'Confirm treatment support ' => '',
  'E-Mail' => '',
  'For authorization in the system {tag} use the following login details: ' => '',
  'If less than 50 people vote for this letter, you can put together a public appeal yourself, print it, sign it, and send it by mail. In this case, the letter will contain not only your opinion, but it will also show the votes of other citizens who voted for it.' => '',
  'If less than 50 people vote for this subject, you can put together a public appeal yourself, print it, sign it, and send it by mail. In this case, the letter will contain not only your opinion, but it will also show the votes of other citizens who voted for it.' => '',
  'If more than 50 people support
// This appeal, <br>
// It will be formalized on the official form and sent by registered mail to the responsible person.' => '',
  'If this message was sent to you by mistake and you don`t want to support the issue in question, please just ignore this message.' => '',
  'If this message was sent to you by mistake and you don`t want to support the petition in question, please just ignore this message.' => '',
  'Kind regards, ' => '',
  'On {siteName} created an appeal based on {basement} "{title}" ' => '',
  'On {siteName} created based on the event {basement} "{title}" ' => '',
  'Post the information about your appeal in social networks through the automatic publication buttons on the issue’s page' => '',
  'Posted collective treatment of citizens {recipient} ({department}) ' => '',
  'See the page of the petition' => '',
  'Subscribe to ' => '',
  'To get the maximum support, you can:' => '',
  'To make your vote count, please follow the link' => '',
  'You (or, maybe, someone on your behalf) have supported the petition in the system' => '',
  'Your appeal' => '',
  'Your appeal is published on {siteName}' => '',
  'Your registration data in the system {siteName} ' => '',
  'an appeal has been created' => '',
  'an event has been created' => '',
  'is published' => '',
  'recommends you, first of all, to attract the support of those who is interested in solving the problem like you.' => '',
  '{n} Sent a letter on the issue {subject} | {n} Sent letters to the problem {subject} | {n} Sent messages on the issue {subject} ' => '',
);
