<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Address can not be edited and deleted, since an already formed' => '',
  'Address can not be edited, because it has supported' => '',
  'Are you sure you want to delete this content?' => '',
  'Asks' => '',
  'Author' => '',
  'BUDGET' => '',
  'Budget' => '',
  'Cancel' => '',
  'Citizen' => '',
  'Copy' => '',
  'Day' => '',
  'Delete' => '',
  'Edit' => '',
  'Event' => '',
  'Guest' => '',
  'Issue' => '',
  'It may be the address of your home, your workplace or your children’s school.' => '',
  'Letters' => '',
  'Link' => '',
  'Local' => '',
  'Mark the places you care about. You’ll receive notifications about the events and the news from these places.' => '',
  'Month' => '',
  'Nobody' => '',
  'Organizator' => 'Organizer',
  'Personal Information' => '',
  'Petition' => '',
  'Poll' => '',
  'Project' => '',
  'Registration Information' => '',
  'Reports' => '',
  'TO:' => '',
  'The city, where the organization ' => '',
  'What will the money be spent on?' => '',
  'Year' => '',
  'You can`t edit the poll because people have already voted.' => '',
  'You participate in the life of' => '',
  'Your passport details are pending. Please wait.' => '',
  'female' => '',
  'male' => '',
  'project on making the city better' => '',
);
